name: PyPI publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip
    
    # build the package with flit
    - name: Build package
      run: pip install build && mv dool dool.py && python -m build

    # publish with https://docs.pypi.org/trusted-publishers/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        name: pypi
        url: https://pypi.org/p/dool
